apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-danis
  namespace: missisipi
  labels:
    app: nginx-danis

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-danis
  template:
    metadata:
      labels:
        app: nginx-danis
    spec:
      containers:
      - name: nginx-danis
        image: nginx:1.16
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  namespace: missisipi
  name: lb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: nginx-danis
  type: LoadBalancer
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Namespace
metadata:
  name: missisipi
