apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydeamon
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
      - name: danis
        image: nginx
        
        