apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-frontend
  labels:
    env: development

spec:
  replicas: 2
  selector:
    matchLabels:
     env: development
  template:
    metadata:
      labels:
        env: development
    spec:
      containers:
      - name: http
        image: httpd:2.4.54
        env:
         - name: TIER
           value: "frontend"
         - name: GROUP
           value: "22c"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc