apiVersion: v1
kind: Pod
metadata:
  name: mysqldb-danis
spec:
  containers:
  - name: mysqldb-danis
    image: mysql:5.6
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-pass
            key: password
    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: cXdlcnR5dWlvcA==
