apiVersion: v1
kind: Pod
metadata:
  name: io-intense
spec:
  containers:
    - name: task-pv-container
      image: alpine:latest
      command: ["sh", "-c"]
      args: ["hostname >> /opt/myhostnames ; sleep 60"]
      volumeMounts:
      - name: my-volume
        mountPath: "/opt"
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: fast

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 22c-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard