apiVersion: v1
kind: deployment
metadata:
  name: danis
  labels:
    color: green
spec:
  containers:
  - name: danis
    image: httpd
    labels:
      color: green
    sector: 
      env: dev
    ports:
      - containerPort: 80
        name: http-web-svc
  replicas: 3

---
apiVersion: v1
kind: Service
metadata:
  name: danis-nodeport-service
spec:
  sector: 
    env: dev
  type: NodePort
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    nodePort: 31000
    targetPort: 80