apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 22c-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard