apiVersion: v1
kind: Pod
metadata:
  name: redis-danis
spec:
  containers:
    - name: redis-secret-danis
      image: redis:5.0.4
      envFrom:
       - secretkeyRef:
            name: redis-secret        
       
      
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  api_token: Zmhkc2NjYmNncjQzOWQK
  db_hostname: cmVkaXNfZGIuZXhhbXBsZS5jb20=
  db_password: U3Ryb25nREJQYXNzd29yZCA=